### ISSUE TITLE
Suggestion to make the rendered pdf more compact

### ISSUE THREAD

**Issue by ToonHub** [inbo/protocolhelper#109]
As the pdf-version will be used for printing the protocol I suggest to make the pdf more compact by not starting a new page with each main header

**Comment by hansvancalster** [comment]
But what if you only want to print a particular chapter? In that case, it makes more sense to start each chapter on a new page to get the best layout and most compact print on paper. For instance, I imagine it often suffices for field workers to only print chapters "Werkwijze" or even only "Samenvatting" as a reminder of what to do/steps to take.

**Comment by hansvancalster** [comment]
Closing this issue because I prefer that individual chapters start at the top of a page so that they can be printed separately.
