### ISSUE TITLE
add appendix chapter to spp template?

### ISSUE THREAD

**Issue by hansvancalster** [inbo/protocolhelper#121]
Suggestion from @Florian9041 to add an Appendix chapter (which should only be rendered if it has content) before the subprotocols chapter (similar to templates for sfp).

@florisvdh do you maybe remember if there was a reason why we did not include this initially?

**Comment by florisvdh** [comment]
> @florisvdh do you maybe remember if there was a reason why we did not include this initially?

No I don't remember, nor imagine why we would not want that.
