### ISSUE TITLE
renderen van protocols met referenties faalt

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/protocolhelper#122]
Renderen van een nieuw protocol met referenties faalt, maar bij tests ontdekten we ook dat het renderen van de bestaande protocols faalt als hier referenties in opgenomen zijn (zowel `.bib` als `.yaml`).  De foutmelding is `! LaTeX Error: Lonely \item--perhaps a missing list environment.`, en er wordt hierbij gerefereerd naar `\bibitem[\citeproctext]{ref-xxx2012}`, verwijzend naar de eerste referentie van het rapport in kwestie.  Het lijkt er dus op dat `\bibitem` niet herkend wordt of zoiets.  Als ik hetzelfde bookdown-project run in een ander project om renv te omzeilen, krijg ik dezelfde foutmelding; @wlangera kan in andere bookdown-projecten wel rapporten met referenties renderen.  Het probleem treedt zowel op onder Windows als onder Linux, waardoor een ontbrekende dependency van een tex-package minder waarschijnlijk lijkt (omdat Linux andere software gebruikt).

Na een halve dag zoeken hebben we de oorzaak niet kunnen achterhalen, mogelijk conflicterende versies van pandoc, tex, R-packages?  [Hieruit](https://github.com/mitchelloharawild/vitae/issues/246) leid ik af dat er in pandoc enkele versies geleden wat veranderd is, misschien is dat nog niet in alle R-packages aangepast, of te recent waardoor het nog niet in de renv opgenomen is?  Of is er een probleem met de layout of volgorde van de verschillende onderdelen van het rapport, zoals [hier](https://github.com/rstudio/bookdown/issues/1403) blijkbaar de oorzaak van een probleem is?  [Deze recente post](https://forum.posit.co/t/compilation-failure-caused-by-bibliography-in-rstudio/188833) lijkt over een gelijkaardig probleem te gaan, dus evt. in de gaten houden voor een oplossing?

@wlangera Vul jij aan wat je je nog herinnert van de testen?

@hansvancalster Ik hoop dat jij dit kan oplossen?  Best even proberen tot je zo'n protocol lokaal gerenderd krijgt (zonder renv), lijkt mij.  Of de vergelijking maken met een ander rapport dat je lokaal wel kan renderen?

**Comment by hansvancalster** [comment]
> Na wat verder opzoekwerk, heb ik gevonden dat het met de LaTeX template te maken heeft. Zie [jgm/citeproc#135](https://github.com/jgm/citeproc/issues/135). In het protocolhelper package zit een [template](https://github.com/inbo/protocolhelper/blob/main/inst/pandoc/inbo_protocol.tex) die dus moet aangepast worden.
> 
> Ik heb dit getest door in de spp-002-nl branch het protocol te renderen (dit geeft inderdaad die foutmelding). Vervolgens in het .tex bestand de code voor de CSL environment aangepast (vervanging doen zoals in [jgm/citeproc#135](https://github.com/jgm/citeproc/issues/135)) en dan op de compile pdf knop gedrukt. Dit werkt!

@ThierryO misschien is dit ook nodig voor de pandoc templates in INBOmd?

**Comment by ThierryO** [comment]
Ik verwacht geen INBOmd issue omdat ik reeds vertrok vanaf pandoc 3.1.8
