### ISSUE TITLE
List dependencies

### ISSUE THREAD

**Issue by ThierryO** [inbo/protocolhelper#17]
Make sure that all packages required to render the protocols are listed in `DESCRIPTION`.
Add them under `Suggests:` if the're not strictly required for `protocolhelper`.

Required for #16 and inbo/protocols#3

**Comment by hansvancalster** [comment]
This should be ok when PR #9 is merged to master

**Comment by hansvancalster** [comment]
@ThierryO I think we need to reconsider this. The DESCRIPTION file of the `protocolhelper` package only lists the packages that are required by the functions in the package. The protocols themselves may however require additional packages if these are used in R chunks inside the Rmarkdown files. This is for instance the case for https://github.com/inbo/protocols/pull/33 which depends on spatstat.

In https://github.com/inbo/protocols/blob/master/.github/workflows/generate-artifact-pr.yml I deal with this via a DESCRIPTION file added to the `protocols` repo (although not a package, just a way to allow querying the repo package dependencies).

What would be the best way to deal with this? What else is still required to make the machinery to publish protocols to protocols-website work (do we need to setup a github action for this in protocols repo)? What can I do to help?

**Comment by ThierryO** [comment]
It will be easier and faster to use [NARA-2020](https://github.com/inbo/nara-2020) as example.
1. It renders the Rmd's based on an [script](https://github.com/inbo/nara-2020/blob/main/render.R) with custom [functions](https://github.com/inbo/nara-2020/blob/main/render_functions.R). User can use the same script to test things local.
2. Store the dependecies via [renv](https://github.com/inbo/nara-2020/tree/main/renv).
3. The [github actions](https://github.com/inbo/nara-2020/tree/main/.github/workflows) use the dedicated [Docker](https://github.com/inbo/nara-2020/blob/main/Dockerfile) based on the `renv.lock` file. The [entrypoint](https://github.com/inbo/nara-2020/blob/ef39e32b8c69519d5b2856e4e782c0114f5caad1/entrypoint.sh#L18) of the Docker uses the `render.R` script from them repo itself.
4. To get everything working you need a custom [github action](https://github.com/inbo/actions/tree/master/render_indicator).

The only thing that might cause a problem are packages that need extra system dependencies. You either need to install those first in the Docker via a separate PR and merge that PR first. Or we need to push the new Docker image manually (which only Floris and I can). Note that every merge to the main branch will overwrite the current (manual) Docker image.

**Comment by hansvancalster** [comment]
Thanks.

1. is OK, we have protocolhelper:::render_release() for publication and protocolhelper::render_protocol() for the user to test locally
2. if I follow, that means we need to setup renv on the protocols repo
3.  Trying to understand this - I find it complicated. I think that in step 4 arguments are passed on to the stuff in step 3 (referred to as $1 $2 and $3)? I am not sure if in this workflow the published versions are pushed to a separate read-only repository (i.e. in our case that would be the protocols-website repo). Is this the case?

**Comment by ThierryO** [comment]
The example I gave places the rendered version in the same repo, but a different branch. I can write the custom entrypoint.sh if you want to go this road.

**Comment by ThierryO** [comment]
First of all we'll need at least one branch with a wroking renv setup. And this should be the next branch to be merged into the main branch.

**Comment by hansvancalster** [comment]
Great! With your help I'm sure we can do this. I will put a working renv setup in https://github.com/inbo/protocols/pull/33 (probably this week).

**Comment by hansvancalster** [comment]
The machinery has been setup, so closing here.
