### ISSUE TITLE
Render `NEWS.Rmd` of individual protocols

### ISSUE THREAD

**Issue by ThierryO** [inbo/protocolhelper#18]
Render each `NEWS.Rmd` to `publish/protocol_code/index.html`. This yields an overview page with every version on the protocol. It should link to the actual protocols in `publish/YYYY.NN/index.html`

Required for inbo/protocols#3

**Comment by hansvancalster** [comment]
@ThierryO Currently the template includes a `00_NEWS.Rmd` chapter. See 9c7293e. So the changes compared to previous versions of a protocol will be rendered as the first chapter of the protocol.

The `render_all` function will generate the following:

````
publish
    | - 2020.01
           | -thematic
                  | - 01-generic
                          | - sfp-001_shorttitle_nl
                                      | - sfp-001_shorttitle_nl.html
                          | - ...
                 | - ....
         | - project
                | - mnm
                       | - spp-001_shorttitle_,nl
                                 | - spp-001_shorttitle_,nl.html
                          | - ...
                 | - ....
````

That means bookdown is setup to return a single html page for reasons explained [here](https://github.com/inbo/protocolhelper/pull/9#issuecomment-603808842).

So we don't yet have `index.html` files in this structure. Now you know the above, can you advice what would be the best way to proceed regarding your issue?

**Comment by ThierryO** [comment]
Keep it simple: rename or copy the .html file to index.html. With an index.html, the folder name redirects to the index.html file, otherwise you get a 404 error.


I had this structure in mind for the publish folder
```
- 2020.01
    - index.html # the protocol updated in 2020.01
- 2020.02
    - index.html # the protocol updated in 2020.02
- 2021.01
    - index.html # the protocol updated in 2021.01
- sfp-001_shorttitle
    - index.html # content of NEWS.Rmd for sfp-001 and links to the relevant versions.
- spp-001_shorttitle
    - index.html # content of NEWS.Rmd for spp-001 and links to the relevant versions.
```

This gives the user two entry points for a protocol a) its version number b) its name

**Comment by hansvancalster** [comment]
I think I will go for the following structure:

````
- 2020.01
    - index.html # the protocol updated in 2020.01
- 2020.02
    - index.html # the protocol updated in 2020.02
- 2021.01
    - index.html # the protocol updated in 2021.01
-thematic
    - 0-generic
        -  sfp-001_shorttitle
            - index.html # content of NEWS.Rmd for sfp-001 and links to the relevant versions.
        - ....
    - ....
- project
    - mnm
        - spp-001_shorttitle
            - index.html # content of NEWS.Rmd for spp-001 and links to the relevant versions.
         - ...
     - ....
````
