### ISSUE TITLE
Tests are not triggered for all pull requests

### ISSUE THREAD

**Issue by florisvdh** [inbo/protocolhelper#29]
It seems that tests are only triggered for PRs that go directly to master. I suggest to do it for all PRs.

**Comment by ThierryO** [comment]
Are you refering to docker builds?

**Comment by florisvdh** [comment]
Yes, these should come up as check results at commit level in GitHub, for branches and pull requests. If you look at [the closed pull requests overview](https://github.com/inbo/protocolhelper/pulls?q=is%3Apr+is%3Aclosed), you can see that only a small part of the pull requests has a green tick symbol. So it seems that in some branches / PRs the checks were triggered, and not in others.

**Comment by ThierryO** [comment]
Something got wrong in the connection between Docker and GitHub. This should be solved. Every new PR should trigger a build on Docker.

**Comment by florisvdh** [comment]
When comparing #37 with #39, it may be that only PRs to `master` trigger the checks, while all PRs should. #39 should have errored (https://github.com/inbo/protocolhelper/pull/39#discussion_r574411079).

**Comment by ThierryO** [comment]
You'll need to update the GitHub action. [Currently](https://github.com/inbo/protocolhelper/blob/ec6361795ef75f103cf1abb555d3d0fe201b8dfd/.github/workflows/pkgdown.yaml#L3) is defined to only run when pushed to master. Have a look at https://github.com/inbo/checklist/tree/master/.github/workflows for inspiration on other options.  You can find more options in the [documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on).

**Comment by florisvdh** [comment]
The `pkgdown.yaml` workflow you refer to should effectively run only when pushed to `master` - it deploys the website (and does not check the package). There are no other Actions present.

However my comment is about the check that appears to run at dockercloud (see #37 vs #39):

![afbeelding](https://user-images.githubusercontent.com/19164640/108397834-aea89f00-7218-11eb-89b8-ad65fae57f6b.png)

**Comment by ThierryO** [comment]
I've updated the build rules on docker

**Comment by florisvdh** [comment]
:+1:
