### ISSUE TITLE
Test details cannot be inspected

### ISSUE THREAD

**Issue by florisvdh** [inbo/protocolhelper#30]
It appears that the test details are not public (login needed).

**Comment by ThierryO** [comment]
That seems to be the standard policy with Docker. The public view of the image is https://hub.docker.com/r/inbobmk/protocol/builds.

Note that the're something wrong with the link they provide to the CI. I get a 404 even when I'm logged into Docker.

I can add you to the Docker organisation, if you provide me with your login.

**Comment by florisvdh** [comment]
Huh, it seems that I already had a loginname. I'll email it.
