### ISSUE TITLE
Accommodate for author affiliations

### ISSUE THREAD

**Issue by florisvdh** [inbo/protocolhelper#32]
@ToonHub suggested (by email) it would be nice to allow author affiliations.

An idea: `create_xxx()` could check for the existence of a file (in a protocols repo) with the (current) author affiliations (the format of the file needs to be specified). If there's a match with authors (e.g. based on names or ORCID or just author-ID) inputted to `create_xxx()`, then the function could load the affiliations.

Affiliations could e.g. look like:

- ID
- first name
- initials
- last name
- organization
- address
- country
- ORCID ID

**Comment by ThierryO** [comment]
I'd only enforce the ORCID. You can get the other information from ORCID. Have a look at the [`rorcid`](https://www.rdocumentation.org/packages/rorcid/versions/0.7.0) package

**Comment by hansvancalster** [comment]
It is now possible to pass `name` and `orcid` via `protocolhelper::create_protocol()`. Done in #51.
