### ISSUE TITLE
Suppress split_chapters() warning

### ISSUE THREAD

**Issue by florisvdh** [inbo/protocolhelper#33]
Given the current protocol templates, I think the following warning will always return:

```
Warning message:
In split_chapters(output, gitbook_page, number_sections, split_by,  :
  You have 14 Rmd input file(s) but only 13 first-level heading(s). Did you forget first-level headings in certain Rmd files?
```

Consequently it would be nice if we could suppress (just) this one. Not sure whether it would be easy to be that selective.

**Comment by hansvancalster** [comment]
closed by #37
