### ISSUE TITLE
Use `distill` package?

### ISSUE THREAD

**Issue by hansvancalster** [inbo/protocolhelper#38]
https://blog.rstudio.com/2020/12/07/distill/
https://rstudio.github.io/distill/

This looks like it could be very interesting for the protocols website and protocol articles.
The `distill::distill_article()` has about the same functionalities as `bookdown::git_book()` that we currently use, but there are some benefits that drew my attention:

- `distill::distill_website()` for making an attractive website (no dependencies like Hugo, ... needed). See https://rstudio.github.io/distill/website.html
- extended yaml author fields including: first_name, last_name, url, affiliation, affiliation_url, orcid_id
- many other nice features (asides, tables and figures that can be wider than text, ...)

@ThierryO @florisvdh @ToonHub ?

It would take some work to refactor everything, but if we decide to do it, we better do it in this early phase. It is also possible to [keep using `bookdown::git_book()`](https://rstudio.github.io/distill/website.html#alternate-formats) for the protocol templates and combine this with `distill::distill_website()` for building the website. That road could also be considered in a later stadium (I think).

**Comment by florisvdh** [comment]
Thanks for pointing at this possibility @hansvancalster. I agree it is worth exploring this route, if you can find some time. Attractive visuals certainly make the difference to people! At some stage we could also engage with artistic colleagues / webdesigners for further improvement.

**Comment by florisvdh** [comment]
The affiliation options of `distill` seem a solution to #32 .

**Comment by hansvancalster** [comment]
Some drawbacks observed so far:

- no support for internationalization
- unlike `bookdown::git_book()`, a single Rmd file should be used for `distill::distill_article()`
- the example template  (file -> rmarkdown -> from template -> distill_article) does not render on my laptop (Error in parse(text = x, keep.source = TRUE) :   <text>:3:14: unexpected '|'2: title: "Untitled"3: description: |): that's odd...

Especially the second point is going to have a lot of effect on `protocolhelper` functions if we were to switch. So, curbing my own enthusiasm a bit...

**Comment by ThierryO** [comment]
Keep in mind that this package will want to override the existing html files. While we want to keep old versions next to the new ones.

**Comment by hansvancalster** [comment]
Good catch. That makes this a path we don't want to take. I'm going to close the issue.
