### ISSUE TITLE
protocol: pdf version

### ISSUE THREAD

**Issue by hansvancalster** [inbo/protocolhelper#40]
We decided to only make html versions of protocols (`bookdown::gitbook`), because it is often a major hassle to also provide `bookdown::pdf_book`  (common complicating factors: latex-dependencies missing, layout tweaks needed, interactive tables or figures, ...).
However, sfp-type protocols will be one html page (or one html page as a subprotocol in spp-type protocols), the print to pdf capacities of webbrowser can be used if this is really needed. 
We could add a section or a separate tab to the homepage of the protocols-website to explain this?

**Comment by hansvancalster** [comment]
> However, sfp-type protocols will be one html page (or one html page as a subprotocol in spp-type protocols), the print to pdf capacities of webbrowser can be used if this is really needed.

I've actually now tested if print as pdf from chrome works, but it doesn't (it does not print everything, just what fits on one pdf page).  https://github.com/yihui/xaringan/wiki/Export-Slides-to-PDF lists several alternative ways to export to pdf.

**Comment by florisvdh** [comment]
ctrl+shift+P ?

**Comment by hansvancalster** [comment]
ctrl+A followed by ctrl+shift+P and then select print "selection" half works. All text and tables are exported to pdf, but figures are missing (probably because the html is not self-contained).

**Comment by hansvancalster** [comment]
For future reference: 

- https://github.com/RLesur/weasydoc
- https://gitlab.pagedmedia.org/tools/pagedjs-cli

**Comment by hansvancalster** [comment]
A simple solution that seems to work fine via a Chrome extension: [print friendly & pdf](https://www.printfriendly.com/)

**Comment by florisvdh** [comment]
> A simple solution that seems to work fine via a Chrome extension: [print friendly & pdf](https://www.printfriendly.com/)

More generally, it's a webbrowser extension, there's some choice:

![afbeelding](https://user-images.githubusercontent.com/19164640/124445234-aa23f380-dd7f-11eb-82f5-3662dbb8e4f5.png)

**Comment by hansvancalster** [comment]
We decided to render protocols to both html and pdf, so closing this issue.
