### ISSUE TITLE
update check on different r operating system

### ISSUE THREAD

**Issue by hansvancalster** [inbo/protocolhelper#49]
We should remove check on old ubuntu in next version of the package:

https://github.com/inbo/protocolhelper/blob/6bede8ee4c552f6d24afa1fbc98479db22d315ff/.github/workflows/check_on_different_r_os.yml#L26

**Comment by hansvancalster** [comment]
Fixed in #51

**Comment by florisvdh** [comment]
Note that the (two-yearly) Ubuntu LTS releases are supported for 5 years (so 18.04 = Bionic expires only in 2023; it's not at all outdated).

A problem however with the code line cited above was the RSPM URL to get binary R packages, which refers the R packages for 16.04 = Xenial (expired 2021). Regarding R, instead of 'oldrel' you could as well check 'release' on 18.04.

**Comment by hansvancalster** [comment]
Could be, but is it worth the extra CPU time given the other check on Ubuntu? I don't see the reason why these workflows always seem to include two versions of Linux-based OS whereas only one version of macOS or Windows. In case you think it is needed, can you give me the correct line of code to use?

**Comment by florisvdh** [comment]
'Needed' will always be debatable. Also, there are many Linux distributions out there (not only the Debian-based like Ubuntu) plus R still supports other Unix-alikes as well, such as FreeBSD and others. So one could test on more systems than Win+MacOS+Ubuntu.

So for checking it depends on your intended audience of the package. If the Linux users you want to support (at INBO and elsewhere) always use an Ubuntu (based) distribution, it makes sense to do checks for each currently supported LTS version, as not everyone will upgrade its Ubuntu version every 2 years. But that's up to you anyway. A correct specification for Bionic, using current R release, is [here](https://github.com/inbo/n2khab/blob/15faf9314367fa52095bba3a8653dd444673c290/.github/workflows/R-CMD-check.yaml#L19).

Regarding Windows & macOS, I don't know whether older (but still supported) versions are available at GHA, but if so then that would make sense as well. If not, that may be the reason why often different Ubuntu versions are tested, and not Win/Mac.

**Comment by hansvancalster** [comment]
Given that my intended audience is INBO employees and the only INBO employees I know who use Ubuntu tend to upgrade their OS on a regular basis 😉 , I just stick with the current configuration 😸  and only consider expanding to other OS if there are requests for it.
