### ISSUE TITLE
docker builds

### ISSUE THREAD

**Issue by ThierryO** [inbo/protocolhelper#50]
The docker image will only build on either the `main` branch or branches with a name starting with `docker`. This is AFAIK the only efficient why to avoid Docker builds on the `gh-pages` branch (which doesn't make sense).

**Comment by hansvancalster** [comment]
Could this also be the reason why this failed: https://github.com/inbo/protocolhelper/runs/2708395704?check_suite_focus=true?
It happened after upgrading the checklist package and pushing the changes to a dev_0.1.6 branch.

**Comment by ThierryO** [comment]
Something went wrong building checklist in its Docker image.

**Comment by ThierryO** [comment]
Problem solved.

**Comment by hansvancalster** [comment]
@ThierryO should this issue remain open or can it be closed?

**Comment by ThierryO** [comment]
You can close it. It was intended as informational.

**Comment by hansvancalster** [comment]
OK thanks!
