### ISSUE TITLE
`check_frontmatter()`: error on version number

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/protocolhelper#61]
Just a detail: after creating a protocol with `create_protocol()`, running `check_frontmatter()` throws the error `Error: str_detect(string = yml$version_number, pattern = "^\\d{4}\\.\\d{2}$") is not true`.

First remark: the error message is not very informative.
Second remark: after removing `.dev` at the end of the version number, the error is still thrown, apparently the version number has to be written between "double quotes".

I don't know if these double quotes are really needed, and if so, if it is possible to already add them when creating the protocol with `create_protocol()`?  If they are needed and adding them is not possible, I would suggest to at least mention in the error message that double quotes should be added.

**Comment by hansvancalster** [comment]
We can probably just change add `as.character()`:
`str_detect(string = as.character(yml$version_number), pattern = "^\\d{4}\\.\\d{2}$")`
We can add a more informative error message in the corresponding `assert_that(..., msg = ...)` statement

**Comment by ElsLommelen** [comment]
Problem only occurs with number `00` in the end (e.g. version number `2022.00`), which is not intended to be used, so a clear error message suffices.
