### ISSUE TITLE
bookdown filenames versus protocol subtitles

### ISSUE THREAD

**Issue by ToonVanDaele** [inbo/protocolhelper#65]
Some bookdown file names are very different from the titles in the protocol. This is a bit confusing. Maybe the file names or the titles can be changed. Examples: stappenplan -> werkwijze, materialen -> benodigdheden

**Comment by hansvancalster** [comment]
This will be fixed when #71 is merged

**Comment by hansvancalster** [comment]
Should be fixed in 5ebce74
