### ISSUE TITLE
Standard structure of SOP, SAP, SFP, SPP - to be discussed?

### ISSUE THREAD

**Issue by Eveltjen00** [inbo/protocolhelper#78]
I think it would be worthwhile brainstorming on the structure of the documents so they are applicable to all teams/procedures. Personally, I prefer a SOP that is to the point; with extra information (definitions, context) in the back/appendices for completeness.

1. Main changes compared to previous version (so that someone familiar with the procedure, knows what has changed)
2. Abstract (= Goal, Scope, Not in Scope + where to find information on what's not in scope if existing)
3. Preparations 
- Safety; vaccinations, protective clothing, warnings of dangerous chemicals, emergency protocols (should be in the beginning!)
- Material (Equipment, Labeling, Data registration (GPS, sampling table, tablet, phone, …))
- Human resources; Which roles and why? Minimal number of people needed for this procedure? Skillset/training needed for this procedure?
- Dependencies on other procedures: Should another procedure be known/studied prior to executing this procedure? 
4. Visualized procedure - Flowchart (can be optional but should be encouraged when helpful)
5. Step-by-step procedure - written text (including quality assurance) and best is also to include visual aid (photo's, diagrams, ..)
6. Definitions
7. References
8. Appendices (including principles, context, more explanation, perhaps extra photos, ..) 

ps: this structure does not apply to SIPs.

To be discussed?

**Comment by florisvdh** [comment]
> it would be worthwhile brainstorming on the structure of the documents

Always :+1:. Thanks for contributing ideas BTW. I assume @hansvancalster will come back to this.

**Comment by hansvancalster** [comment]
Thanks for opening this issue. I will schedule a live meeting to discuss this further. We can then report back here with whatever we decide to do.

**Comment by hansvancalster** [comment]
We discussed this and decided to add this next to the other protocol templates as a "generic" template.
This will become part of v0.4.0 of protocolhelper.
