### ISSUE TITLE
update_version_number() commits previous changes as well

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/protocolhelper#79]
When I perform another change on my repo before running `update_version_number()` (e.g. deleting a file in the repository different from the `index.Rmd` that is changed by the function), this change is added as well to the commit that is produced by the function.  This unexpected behaviour doesn't give any warning.
In my opinion this problem could largely be avoided by only staging the changed file `index.Rmd` before committing (instead of committing all possible changes in the repository).  This is not yet covering changes in the file itself, but in this case the behaviour is less 'unexpected'.  It would of course be user friendly to give a warning in this case, if only staging the true change is no option.

**Comment by hansvancalster** [comment]
solved by #80
