### ISSUE TITLE
Small remark on error message

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/protocolhelper#86]
When running function `get_path_to_protocol()`, I was surprised to get [the error message `Provide a short title`](https://github.com/inbo/protocolhelper/blob/main/R/get_path_to_protocol.R#L66) when I apparently did not give an existing path (due to a coding mistake).  It would be helpful to precede this error message with `The provided path does not exist.` or something similar that makes users aware of the fact that the message is dropped because they made a mistake in the path.  If they understand this, they can opt to correct the path name or give a short title instead.

**Comment by hansvancalster** [comment]
Good point. I have improved the error message (the change will be in v0.4.1).
