### ISSUE TITLE
dockerfile not needed?

### ISSUE THREAD

**Issue by hansvancalster** [inbo/protocolhelper#98]
There is a [dockerfile](https://github.com/inbo/protocolhelper/blob/main/Dockerfile) in the repo for this package, but it is unclear why and if it is needed. @ElsLommelen can you confirm that this file can be removed? If yes, than the associated inbobmk/protocol build on docker needs to be removed too.

**Comment by ElsLommelen** [comment]
To be honest, I don't know the purpose of that dockerfile.  It makes a 'computer' with protocolhelper installed, and it is pushed to dockerhub (name 'protocol', whereas the new automations are in 'protocols'), but it is no added in inbo/actions.  It is not used in the automation I made, but maybe @ThierryO knows better if is still in use (and where), as he made it 2 years ago?  As far as I see, it is not used.

**Comment by hansvancalster** [comment]
I've made a commit that removes this in the next development version. @ElsLommelen can you remove it in the associated inbobmk/protocol build on docker?

**Comment by ThierryO** [comment]
It seems you are using the docker at inbo/protocolsource.  One is sufficient. Keep in mind that the docker image is updated when the main branch is updated. When do you want a new docker image? Upon a push to the main branch of this repo or upon a push to the main branch of inbo/protocolsource?

**Comment by ElsLommelen** [comment]
@ThierryO I want the docker at inbo/protocolsource to be updated upon a push to the main branch of inbo/protocolsource (which is the case now, so I want it to stay like this).

I don't know nothing about the docker in this repo (inbo/protocolhelper): you made it 2 years ago, and I don't know where it is used (if it is used at all).  Apparently it was updated 7 days ago, so most likely together with the most recent push to the main branch of this repo, but as I don't know where it is used, I find difficult to tell when it should be updated.  If not used at all, I suppose it can be removed both in this repo and on dockerhub?  So it would be helpful if you could explain why this docker is made, and where it is (possibly) used.

**Comment by ThierryO** [comment]
IMHO it makes more sense to place the Docker in this repo. Then this repo contains all the code and tools to render the protocols and inbo/protocolsource only contains the content of the protocols. I see no need to rebuild the docker when someone publishes a new protocol.

**Comment by hansvancalster** [comment]
We discussed this live and this issue can be closed.
